"""Auto migration on container start

Revision ID: b6d082581a1b
Revises:
Create Date: 2025-11-06 16:21:38.980242

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6d082581a1b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spreadsheets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cells",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("spreadsheet_id", sa.Integer(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("col_index", sa.Integer(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("formula", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["spreadsheet_id"], ["spreadsheets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "row_index", "col_index"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cells")
    op.drop_table("spreadsheets")
    # ### end Alembic commands ###
